# Generated by Django 4.2.25 on 2026-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_exercise_difficulty_score_exercise_total_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="cardio_intensity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exercise",
            name="core_involvement",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exercise",
            name="flexibility",
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name="exercise",
            name="lower_body_involvement",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exercise",
            name="strength_focus",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="exercise",
            name="upper_body_involvement",
            field=models.IntegerField(default=0),
        ),
    ]
