# Generated by Django 4.2.25 on 2026-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="trainerbooking", name="loyalty_factor",),
        migrations.RemoveField(model_name="trainerbooking", name="preference_factor",),
        migrations.RemoveField(model_name="trainerbooking", name="urgency_factor",),
        migrations.AlterField(
            model_name="trainerbooking",
            name="priority_score",
            field=models.FloatField(default=0),
        ),
    ]
